package com.rank_calaculator.enums;

public enum Types {
    FRIENDLY_OUT_INTERNATIONAL_CALENDAR,
    FRIENDLY_DURING_INTERNATIONAL_CALENDAR,
    GROUP_PHASE_OF_NATIONAL_LEAGUE,
    PLAY_OFF_AND_FINAL_OF_NATIONAL_LEAGUE,
    QUALIFICATION_MATCHES_FOR_CONFEDERATIONS_AND_WORLD_CUP,
    CONFEDERATION_FINAL_UNTIL_QF_STAGES,
    CONFEDERATION_FINAL_FROM_QF_STAGES,
    FIFA_CONFEDERATIONS_CUP_MATCHES,
    FIFA_WORLD_CUP_FINAL_UNTIL_QF_STAGES,
    FIFA_WORLD_CUP_FROM_QF_STAGES
}
